title: "Your blog post title"
date: 2021-05-22
author: konrad
email: konrad343343@gmail.com
theme: minima

# social links
github_username:  Marnigar

show_excerpts: true # set to false to remove excerpts on the homepage
